name: Pack and Comment
# for each PR this workflow builds and then packs a Stencil tarball and then
# posts a comment on the PR with a link to download the tarball, as well as an
# example command for installing the tarball in a project.

on:
  pull_request_target:
    branches:
      - '**'

jobs:
  pack:
    name: Pack and Comment
    runs-on: 'ubuntu-22.04'
    steps:

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies
